// frontend/features/shared/ui/BillingList.tsx
import { services, type ServiceCategoryId } from "../types/services";
import { Icon } from "../icons/Icon";
import { LocalIcon } from "../icons/localIcon";

type Props = {
  titles: string[];
  lists: ServiceCategoryId[];
  colors: string[];
  icons: string[];
  cssStyles: string;
};

export function BillingList({
  titles,
  lists,
  colors,
  icons,
  cssStyles,
}: Props) {
  return (
    <>
      {lists.map((categoryId, index) => {
        const category = services.categories.at(index);
        const items = services[categoryId];
        const color = colors.at(index) ?? category?.color;
        const title = titles.at(index);
        const icon = icons.at(index) as any;

        return (
          <div
            key={categoryId}
            id={category?.id}
            className="bg-custom-white rounded-[33px] p-6 container mx-auto my-5"
          >
            <div className="flex items-center gap-3">
              {icon && <LocalIcon name={icon} size={25} className={color} />}
              <span className="font-bold text-custom-neutral text-sm">
                {title}
              </span>
            </div>
            <div>
              <div className={cssStyles}>
                {items.map((service) => (
                  <div
                    key={service.label}
                    className="grid place-items-center gap-3 text-center"
                  >
                    <a
                      href={service.disabled ? undefined : service.to}
                      className={`transition hover:scale-110 hover:opacity-60 ${
                        service.disabled ? "opacity-40 pointer-events-none" : ""
                      }`}
                    >
                      <LocalIcon
                        name={service.icon as any}
                        size={55}
                        className="w-[70px] h-[70px] p-3 bg-custom-whitesmoke rounded-2xl"
                        // color={color}
                      />
                      <p className="text-xs mt-2">{service.label}</p>
                    </a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        );
      })}
    </>
  );
}

// client/app/components/BillingList.vue
<script lang="ts" setup>
import Services from "~/content/services.json"
const props = withDefaults(defineProps<{
    title: string[],
    list: any[],
    icon?: string[],
    color?: string[],
    cssStyles?: string
}>(), {})
</script>

<template>
    <div :id="String(Services.categories.at(index)?.id)" class="bg-custom-white rounded-[33px] p-6 container mx-auto my-5 " v-for="(item, index) of list"
        :key="index">
        <div class="flex items-center gap-3">
            <AppIcon :name="String(props.icon?.at(index))" size="25" :color="props.color?.at(index)" />
            <span class="font-bold text-custom-neutural text-sm">{{ props.title.at(index) }}</span>
        </div>
        <!-- List -->
        <div>
            <div :class="props.cssStyles">
                <div v-for="service of props.list[index]" class="grid place-items-center gap-3 text-center">
                    <NuxtLink :to="!service.disabled ? service.to : ''" :class="{'opacity-40': service.disabled}" class="transition hover:scale-110 hover:opacity-60">
                        <AppIcon :name="service.icon" size="55"
                        class="w-[70px] h-[70px] p-3 bg-custom-whitesmoke rounded-2xl"
                        :style="{ color: props.color?.at(index) }" />
                    <p class="text-xs mt-2">{{ service.label }}</p>
                    </NuxtLink>
                </div>
            </div>
        </div>
    </div>
</template>
